name: flowery_tts
version: 1.2.0
description: >-
  A free Text-to-Speech service providing 850+ voices with
  English translation support. This package is an unofficial
  wrapper of Flowery TTS API.

repository: https://github.com/priyanuj-gogoi/flowery-tts

environment:
  sdk: ^3.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

topics:
  - api-wrapper
  - free
  - text-to-speech
  - translation
  - tts

dependencies:
  http: ^1.0.0
  meta: ^1.12.0
